name: work
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.2.1
  geolocator_apple: ^2.3.13
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  kakao_flutter_sdk: ^1.9.6
  ulid: ^2.0.1
  http: ^1.2.2
  intl: ^0.20.2
  timeago: ^3.7.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  location: ^7.0.1
  table_calendar: ^3.0.9
  percent_indicator: ^4.2.5
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.4
  provider: ^6.1.5
  lottie: ^3.3.1
  cloud_functions: ^5.5.1


  #background_fetch: ^1.3.0
  #workmanager: ^0.6.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ðŸš€ ì•± ì•„ì´ì½˜ ìƒì„±ìš© íŒ¨í‚¤ì§€ ì¶”ê°€
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/rundventure.png
    - assets/images/rundventure2.png
    - assets/images/running.png
    - assets/images/running2.png
    - assets/images/Open Door.png
    - assets/images/Login-Social-Media.png
    - assets/images/Lock.png
    - assets/images/Hide-Password.png
    - assets/images/googlelogo.png
    - assets/images/kakao.png
    - assets/images/Email.png
    - assets/images/Back-Navs.png
    - assets/images/Account.png
    - assets/images/BackButton.png
    - assets/images/banner.png
    - assets/images/rundventuretext.png
    - assets/images/weight.png
    - assets/images/Height.png
    - assets/images/mainrundventure.png
    - assets/images/mainrundventure2.png
    - assets/images/user.png
    - assets/images/basicuser.png
    - assets/images/alarm.png
    - assets/images/underbar.png
    - assets/images/centerbutton.png
    - assets/images/buttonurrow.png
    - assets/images/underbarhome.png
    - assets/images/underbarchart.png
    - assets/images/buttoncover.png
    - assets/images/runningimage.png
    - assets/images/runningimage2.png
    - assets/images/runningimage3.png
    - assets/images/set.png
    - assets/images/challenge.png
    - assets/images/image 17.png
    - assets/images/image 18.png
    - assets/images/menu.png
    - assets/images/talk.png
    - assets/images/logo.png
    - assets/badges/
    - assets/images/nextbutton.png
    - assets/images/flame.png
    - assets/images/graph.png
    - assets/images/trophy.png
    - assets/images/game2.png
    - assets/images/game3.png
    - assets/images/ghostlogo.png
    - assets/images/soonlogo.png
    - assets/images/Back-Navs-Black.png
    - assets/images/ghostrunpage1.png
    - assets/images/ghostrunpage1-2.png
    - assets/images/ghostrunpage2.png
    - assets/images/ghostrunpage2-1.png
    - assets/images/ghostrunpage3.png
    - assets/images/ghostrunpage3-1.png
    - assets/images/ghostrunconfirmation.png
    - assets/images/ghostrunconfirmation2.png
    - assets/images/runner.png
    - assets/images/ghostrunner.png
    - assets/maps/map_dark.json
    - assets/images/man.png
    - assets/images/signupcom.png
    - assets/images/stretching.png
    - assets/lottie/armsjump.json
    - assets/lottie/legexercise.json
